### ISSUE TITLE
Workaround for the reset button 

### ISSUE THREAD

**Issue by DeepthiSudharsan** [stefanrmmr/streamlit_audio_recorder#12]
I have been trying to use this package for recording and saving audio on Streamlit applications deployed over Azure web apps. I was wondering if there is a workaround for the reset button so that every time the recording is stopped, we do not have to manually reset it. At times when I refresh the whole Streamlit application and run the code again and if, during the previous session, I had not reset the recorder unless I click reset again, it doesn't allow me to record. 

P.S. Also does this work over https? I have been trying it locally so far and was wondering if it would work over the Azure web apps running over HTTPS.

Thanks for the help and for coming up with this useful package!

**Comment by VaysseRobin** [comment]
Hello, is there any workaround on this topic ? I'm facing the same issue.
Thanks for helping :)

**Comment by stefanrmmr** [comment]
Hey @DeepthiSudharsan, 

unfortunately, I was not able to recreate this behaviour of the component in my test deployment. Force refreshing the application (basically like refreshing the browser window so that the app's UI is rendered again from scratch), has led to the component being set back to its initial state (similarly to pressing the reset button). 

You can force refresh (and reset the component) programmatically by including `st.experimental_rerun()` in your code.
